# Generated by Django 4.0.4 on 2022-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(max_length=250, verbose_name='Полная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Сокращенная ссылка'),
        ),
    ]
