# Generated by Django 4.0.4 on 2022-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_agree_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='Згода'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('meal', 'Чоловік'), ('femeal', 'Жінка')], default=None, max_length=100, verbose_name='Стать'),
        ),
    ]
