# Generated by Django 4.0.4 on 2022-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_agree_alter_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='img2',
            field=models.ImageField(default='default.png', upload_to='user_image', verbose_name='Фото профілю'),
        ),
    ]
