# Generated by Django 4.0.4 on 2022-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_img2_profile_agree_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('meal', 'Чоловік'), ('femeal', 'Жінка')], default=True, max_length=100, verbose_name='Стать'),
        ),
    ]
