# Generated by Django 4.0.4 on 2022-05-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
    ]
