# Generated by Django 4.0.4 on 2022-05-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_link_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
